- name: create ec2 and update route53 on allows
  hosts: localhost
  connection: local
  vars:
    aws_region: us-east-1
    ec2_instance_type: t3.micro
    ec2_image: ami-09c813fb71547fc4f
    ec2_count: 1
    route53_zone_id: "Z0806995L2997E89SFOF"
    route53_domain: "kardev.space"
    security_group: sg-0e26215670f90eb6a
    instances:
      - "{{ component }}"
    #  - mongodb
    #  - mysql
    #  - redis
    #  - rabbitmq
    #  - payment
    #  - catalogue
    #  - user
    #  - shipping
    #  - cart
    #  - frontend



  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      state: present
      name: "{{ item }}"
      instance_type: "{{ ec2_instance_type }}"
      security_group: "{{ security_group }}"
      image_id: "{{ ec2_image }}"
      tags:
        Environment: Dev 
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instances

  # - name: print ec2 instances info
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_instances.results }}"

  # - name: print ec2 instances info
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_instances.results }}"

## implement route53 records and for each instance that is not the frontend add a record with private ip address
## for frontend use public ip address

  - name: Add public  ip_address of instances to route53 record
    amazon.aws.route53:
      state: present
      hosted_zone_id: "{{ route53_zone_id }}"
      record: "{{ item.item }}.{{ route53_domain }}"
      type: A
      ttl: 10
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_instances.results }}"
    


  - name: Add private ip_address of instances to route53 record
    amazon.aws.route53:
      state: present
      hosted_zone_id: "{{ route53_zone_id }}"
      record: "{{ item.item }}.{{ route53_domain }}"
      type: A
      ttl: 10
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    when: item.item != "frontend"
    loop: "{{ ec2_instances.results }}"
    

    