- name: Shipping server
  hosts: shipping
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
  - name: Installing maven
    ansible.builtin.package:
      name: maven 
      state: present

  - name: Create a system user 
    ansible.builtin.user:
      name: roboshop
      comment: roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Remove existing shipping.zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: create directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: Download appliction to app directory
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Unzip shipping.zip that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  # - name: Maven clean install
  #   ansible.builtin.shell: |
  #     cd /app
  #     mvn clean install
  #     mv target/shipping-1.0.jar shipping.jar

  - name: Maven clean Install
    ansible.builtin.command: mvn clean install
    args:   
      chdir: /app

  - name: rename shipping.jar
    ansible.builtin.command: mv /app/target/shipping-1.0.jar /app/shipping.jar

  # - name: Copy a "sudoers" file on the remote machine for editing
  #   ansible.builtin.copy:
  #     src: /target/shipping-1.0.jar
  #     dest: /shipping.jar
  #     remote_src: yes

  - name: copy shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: Ensure PyMySQL is installed
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3
    loop:
    - PyMySQL
    - cryptography

  - name: Install my sql
    ansible.builtin.package:
      name: mysql
      state: present

  - name: Import into mysql database
    community.mysql.mysql_db:
      name: all
      state: import
      login_host: mysql.kardev.space
      login_user: root
      login_password: RoboShop@1
      target: /app/db/{{ item }}.sql
    loop:
    - schema
    - app-user 
    - master-data

  

  - name: Reload service shipping, in all cases
    ansible.builtin.systemd_service:
      name: shipping
      enabled: true
      state: started
      daemon_reload: true


